// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDnnMIc86plKoJMuw34zzsItp3f_7ci0',
    appId: '1:503191394482:web:31a68a8c0df37b8ea9d1ab',
    messagingSenderId: '503191394482',
    projectId: 'myportfolio-f3c6d',
    authDomain: 'myportfolio-f3c6d.firebaseapp.com',
    storageBucket: 'myportfolio-f3c6d.appspot.com',
    measurementId: 'G-XE5L4H6Q3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnGCfDJn8Agu1R3PyW-OZ6X1GYTLGea7E',
    appId: '1:503191394482:android:67e072edb1da19c5a9d1ab',
    messagingSenderId: '503191394482',
    projectId: 'myportfolio-f3c6d',
    storageBucket: 'myportfolio-f3c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPAFXmk_CJ7tOJMLYj_lHNMOTsxMH_4bs',
    appId: '1:503191394482:ios:a8e3729ddf823916a9d1ab',
    messagingSenderId: '503191394482',
    projectId: 'myportfolio-f3c6d',
    storageBucket: 'myportfolio-f3c6d.appspot.com',
    iosBundleId: 'com.example.fzyPortfolio',
  );
}
